# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [10]:
def same(x):
    if (x[0] == x[-1]):
        return True
    else:
        return False

# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

print(same(numbers_x))
print(same(numbers_y))
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [13]:
#code here
import numpy as np 
l1 = np.arange(5)
print(l1)
l2 = np.arange(5)
print(l2)

add = l1 + l2
print(add)

prod = l1 * l2
print(prod)


[0 1 2 3 4]
[0 1 2 3 4]
[0 2 4 6 8]
[ 0  1  4  9 16]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [19]:
#code here
l3 = np.arange(12).reshape(3,4)
print(l3)

l4 = np.array([1,2,3,4])
l5 = np.array([5,6,7,8])

hor = np.hstack((l4, l5))
print(hor)

ver = np.vstack((l4,l5))
print(ver)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [1]:
#Code here
products = ['AI Response Simulator', 'Investment Decision']
shopping_cart = []
print("Welcome")
print("Available products:")
for i in range(len(products)):
    print(f"{i+1}. {products[i]}")

while True:
    choice = input("\n Enter the number of products you want to add to the card (or 'q'to quit):")
    if choice.lower() == 'q':
        break

    try:
        choice = int(choice)
        if 1<= choice <= len(products):
            shopping_cart.append(products[choice-1])
            print(f"You have added {products[choice-1]} to your cart")
        else:
            print("Invalid input")
    except ValueError:
        print("Invalid input. Enter a number")


print("You shopping cart contains:")
for i in shopping_cart:
    print(i)

print("Thank you. Byeeeeeee 👋")


    

Welcome
Available products:
1. AI Response Simulator
2. Investment Decision
You have addedAI Response Simulator to your cart
You have addedInvestment Decision to your cart
Invalid input
You shopping cart contains:
AI Response Simulator
Investment Decision
Thank you. Byeeeeeee 👋


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [4]:
#code here
def classify(emails):
    important = ['urgent', 'important', 'immediate']
    promo = ['sale', 'deal', 'offer']
    spam = ['win', 'prize']

    imp_mail = []
    promo_mail = []
    spam_mail = [] 

    for email in emails:
        email = email.lower()
        if any(keyword in email for keyword in important):
            imp_mail.append(email)

        elif any(keyword in email for keyword in promo):
            promo_mail.append(email)
        
        elif any(keyword in email for keyword in spam):
            spam_mail.append(email)

    return imp_mail, promo_mail, spam_mail


In [5]:

emails = ['Urgent meeting tomorrow', 'Big sale on all items', 'You won a prize!']
important_emails, promotions_emails, spam_emails = classify(emails)

print("Important emails:", important_emails)
print("Promotions emails:", promotions_emails)
print("Spam emails:", spam_emails)


Important emails: ['urgent meeting tomorrow']
Promotions emails: ['big sale on all items']
Spam emails: ['you won a prize!']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [6]:
# #code here
dict = {
    'hello' : 'hola',
    'goodbye' : 'adios',
    'please': 'por favor',
    'thank you' : 'gracias'

}

while True:
    word = input("Please enter an english word (or 'x' to exit):")
    if word.lower() == 'x':
        break
    
    trans = dict.get(word)
    if trans:
        print(f"The spanish for {word} is {trans}.")
    else:
        print("unavailable")


The spanish for hello is hola.
The spanish for goodbye is adios.
unavailable


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [3]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
df = pd.DataFrame(data).set_index('Rank')

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
Rank                 
1             82.74  
2             40.24  
3             35.82  
4             33.00  
5             31.37  
...             ...  
16596          0.01  
16597          0.01  
16598          0.01  
16599          0.01  
16600          0.01  

[16598 rows x 10 columns]

In [5]:
df['Global_Sales'].sum()

8920.44

In [9]:
df.iloc[df['Global_Sales'].argmax()][0]

C:\Users\user\AppData\Local\Temp\ipykernel_14524\1699019907.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[df['Global_Sales'].argmax()][0]


'Wii Sports'

In [12]:
df[['NA_Sales', 'EU_Sales', 'JP_Sales']].mean()

NA_Sales    0.264667
EU_Sales    0.146652
JP_Sales    0.077782
dtype: float64

In [18]:
df2 = df.sort_values(ascending=False, by='Global_Sales')
df2['Genre'].head(5)

Rank
1          Sports
2        Platform
3          Racing
4          Sports
5    Role-Playing
Name: Genre, dtype: object

In [31]:
genre = df.groupby('Genre')
genre[['NA_Sales', 'EU_Sales', 'JP_Sales']].sum()

NA_Sales  EU_Sales  JP_Sales
Genre                                     
Action          877.83    525.00    159.95
Adventure       105.80     64.13     52.07
Fighting        223.59    101.32     87.35
Misc            410.24    215.98    107.76
Platform        447.05    201.63    130.77
Puzzle          123.78     50.78     57.31
Racing          359.42    238.39     56.69
Role-Playing    327.28    188.06    352.31
Shooter         582.60    313.27     38.28
Simulation      183.31    113.38     63.70
Sports          683.35    376.85    135.37
Strategy         68.70     45.34     49.46

In [23]:
df.iloc[df['NA_Sales'].argmax()][3]

C:\Users\user\AppData\Local\Temp\ipykernel_14524\3655348471.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[df['NA_Sales'].argmax()][3]


'Sports'

In [25]:
df.tail(10)

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
Rank                              
16591          0.0          0.01  
16592          0.0          0.01  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01  
16598          0.0          0.01  
16599          0.0          0.01  
16600          0.0          0.01

In [32]:
df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)


Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [35]:
df['NA_Sales'].corr(df['EU_Sales'])

0.767726748370264